### ISSUE TITLE
[Feature request] Configure-able task timeout

### ISSUE THREAD

**Issue by nefarius** [bengreenier/vcpkg.nuget#20]
Hey hey!

Fantastic package, it's the glue that was missing for an even more convenient integration into projects!

**But...** 😅 I immediately ran into the [10 minute timeout](https://github.com/bengreenier/vcpkg.nuget/blob/master/InstallTask.cs#L61):

```
Warning	MSB5002	The task executable has not completed within the specified limit of 600000 milliseconds, terminating.
```

I'm building POCO which requires ~12 to 17 minutes to initially build on my machine. The lazy way would ofc. be to just bump the timeout although I guess exposing it as an attribute would allow for more control.

Thanks for reading 🙂

**Comment by nefarius** [comment]
[I implemented it myself](https://github.com/nefarius/vcpkg.nuget/tree/feature/setting/timeout) and can submit a PR if you're interested. Cheers!

**Comment by bengreenier** [comment]
@nefarius wow super sorry I missed this (my github notifications are a bit of a mess) - I actually just stumbled across your usage of this digging through https://github.com/nefarius/Indicium-Supra (awesome project btw), small world. 😸 

I'd love to merge that stuff in, if you have a minute to drop a PR my way. 🚀

**Comment by nefarius** [comment]
Hey hey @bengreenier 🙂 

Thanks for the reply, I myself also suffer from not finding balance on GitHub notifications (you either drown in mails or miss important stuff, grrr).

Small world indeed 😆 

Will craft a PR. Do bear in mind that I'm not an in-depth MSBuild guru so what I've thrown together "just works". I'm certain there are more elegant ways. Am open to feedback ofc.
