### ISSUE TITLE
[Broken CI] latest release modified build location

### ISSUE THREAD

**Issue by bengreenier** [bengreenier/vcpkg.nuget#27]
v1.5.0 modified the location of built binaries which breaks ci and therefore the pipeline. as such, 1.5.0 isn't actually live yet 😞 

I'll try to resolve this ASAP (hopefully in the next few hours)

**Comment by bengreenier** [comment]
ah - the deeper issue here seems to be `vcpkg` has moved to a bin directory of `msbuild.<arch>.<configuration>` - we should probably migrate our build to those folders, and __at minimum__ we'll need to update the `Nuget.vcxproj` that copies things into place for building our nupkg

**Comment by ras0219-msft** [comment]
Sorry for the trouble!

Is there a way that you can just use `./bootstrap-vcpkg.bat` instead of calling MSBuild? In the future, we may move to using CMake on windows, but `./bootstrap-vcpkg.bat` will definitely continue to work (and continue to place the executable in the root).

**Comment by bengreenier** [comment]
No worries @ras0219-msft - that's a great idea, I've opened #29 to track
