### ISSUE TITLE
portfiles outdated

### ISSUE THREAD

**Issue by nefarius** [bengreenier/vcpkg.nuget#30]
Greetings,

IIRC the ports directory is shipped within the final NuGet. Unfortunately a package ([detours](https://github.com/Microsoft/vcpkg/tree/master/ports/detours) in my case) isn't available so is the plan to regularly update this package or how's the plan? 😃 

Cheers

**Comment by bengreenier** [comment]
yes sorry - this isn't something I have time for anymore :(

**Comment by nefarius** [comment]
Understandable, devote your time towards the things that bring you joy 👍
